version: '3.8'

services:
  api:
    build: .
    container_name: django_reportana_api
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # --skip-checks impede o Django de validar migrações no boot
    command: python manage.py runserver 0.0.0.0:8000 --skip-checks
    environment:
      - PYTHONUNBUFFERED=1